# Generated by Django 4.1.1 on 2022-09-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='pic',
        ),
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
