# Generated by Django 4.1.1 on 2022-09-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_movies_pic_movies_rating_movies_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('klass', models.IntegerField(verbose_name='class')),
                ('roll_number', models.IntegerField()),
            ],
        ),
    ]
