# Generated by Django 4.1.1 on 2022-09-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_singer_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='actor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
