# Generated by Django 4.1.1 on 2022-09-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_movies_actor_alter_movies_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='year',
            new_name='release_date',
        ),
    ]
