# Generated by Django 4.1.1 on 2022-09-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_year_movies_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(null=True, upload_to='Movies_image/'),
        ),
    ]
