# Generated by Django 4.1.1 on 2022-10-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='upload_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
