# Generated by Django 4.1.1 on 2022-10-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_author_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
