# Generated by Django 4.1.1 on 2022-10-28 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_blog_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='caption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.caption'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tags'),
        ),
    ]
