# Generated by Django 4.1.1 on 2022-10-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_blog_caption_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
