# Generated by Django 4.1.1 on 2022-10-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_sub_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='category',
            new_name='categories',
        ),
    ]
