# Generated by Django 4.1.1 on 2022-10-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_article_author_alter_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
