# Generated by Django 4.1.1 on 2022-11-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_information', models.TextField(max_length=150)),
                ('product_image', models.ImageField(upload_to='media/products/')),
            ],
        ),
    ]
